# fly.toml file generated for curiopost-inspiration-bot on 2022-09-24T21:40:53+05:30

app = "curiopost-inspiration-bot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"

[experimental]
  allowed_public_ports = []
  auto_rollback = true


